package br.com.rh.enums;

public enum GraduationType {
    UNIVERSITY_GRADUATION,
    COMPLEMENTARY_GRADUATION_SPECIALIZATION,
    COMPLEMENTARY_GRADUATION_MBA,
    COMPLEMENTARY_GRADUATION_MASTERS_DEGREE,
    COMPLEMENTARY_GRADUATION_DOUTORATE_DEGREE,
    COMPLEMENTARY_COURSES,
}
